# NUMPY

NumPy stands for Numerical Python. It is a Python library used for
numerical computations and working with arrays.

It provides fast and efficient operations on large amounts of data.

## INSTALLING NUMPY

pip install numpy

## IMPORTING NUMPY

import numpy as np

## ARRAYS IN NUMPY

A NumPy array is a collection of elements of the same data type.
It supports one-dimensional, two-dimensional, and multidimensional arrays.

## CREATING ARRAYS

### 1. np.array()
Creates a NumPy array from a list or tuple.

### 2. np.zeros()
Creates an array filled with zeros.

### 3. np.ones()
Creates an array filled with ones.

### 4. np.arange()
Creates an array containing values within a specified range.

### 5. np.linspace()
Creates evenly spaced values within a specified interval.

## ARRAY ATTRIBUTES

### 1. ndim
Returns the number of dimensions.

### 2. shape
Returns the dimensions of an array.

### 3. size
Returns the total number of elements.

### 4. dtype
Returns the data type of the elements.

## ARRAY OPERATIONS

NumPy supports arithmetic operations such as addition, subtraction,
multiplication, and division on arrays.

## INDEXING AND SLICING

Indexing is used to access individual elements.
Slicing is used to access a range of elements.

## MATHEMATICAL FUNCTIONS

NumPy provides functions such as sum(), min(), max(), mean(),
sqrt(), and sort().

## RESHAPING ARRAYS

The reshape() function changes the shape of an array without
changing its data, provided the total number of elements remains the same.

## ARRAY JOINING AND SPLITTING

The concatenate() function joins arrays.
The split() function divides an array into smaller arrays.

In [1]:
# Creating a NumPy array

import numpy as np

numbers = np.array([10, 20, 30, 40, 50])

print(numbers)
print(type(numbers))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [2]:
# Creating arrays using NumPy functions

import numpy as np

print(np.zeros(5))
print(np.ones(5))
print(np.arange(1, 11))
print(np.linspace(1, 10, 5))

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1.    3.25  5.5   7.75 10.  ]


In [3]:
# Creating a two-dimensional array

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [4]:
# NumPy array attributes

import numpy as np

arr = np.array([[10, 20, 30], [40, 50, 60]])

print("Dimensions:", arr.ndim)
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Data type:", arr.dtype)

Dimensions: 2
Shape: (2, 3)
Size: 6
Data type: int64


In [5]:
# Indexing and slicing

import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print("First element:", arr[0])
print("Last element:", arr[-1])
print("First three elements:", arr[:3])
print("Elements from index 2:", arr[2:])

First element: 10
Last element: 50
First three elements: [10 20 30]
Elements from index 2: [30 40 50]


In [6]:
# Arithmetic operations on arrays

import numpy as np

a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [11 22 33]
Subtraction: [ 9 18 27]
Multiplication: [10 40 90]
Division: [10. 10. 10.]


In [7]:
# Mathematical functions

import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print("Sum:", np.sum(arr))
print("Minimum:", np.min(arr))
print("Maximum:", np.max(arr))
print("Mean:", np.mean(arr))
print("Square root:", np.sqrt(arr))
print("Sorted array:", np.sort(arr))

Sum: 150
Minimum: 10
Maximum: 50
Mean: 30.0
Square root: [3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
Sorted array: [10 20 30 40 50]


In [8]:
# Reshaping an array

import numpy as np

arr = np.arange(1, 10)

new_arr = arr.reshape(3, 3)

print(new_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
# Joining arrays

import numpy as np

a = np.array([10, 20, 30])
b = np.array([40, 50, 60])

result = np.concatenate((a, b))

print(result)

[10 20 30 40 50 60]


In [10]:
# Splitting an array

import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])

result = np.split(arr, 3)

print(result)

[array([10, 20]), array([30, 40]), array([50, 60])]


In [11]:
# Filtering array elements

import numpy as np

arr = np.array([10, 25, 30, 45, 50, 65])

result = arr[arr > 30]

print(result)

[45 50 65]
